services:
  - type: web
    name: medicine-recommendation-system
    env: python
    plan: free
    rootDir: Medicine-Recommendation-System
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeploy: true
